services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://photo_user:wang619218505@photo-map-db:5432/photomap_db
    container_name: photo-map-next
    env_file:
      - .env.docker
    environment:
      - DATABASE_URL=postgresql://photo_user:wang619218505@photo-map-db:5432/photomap_db
    command: sh -c "npx prisma migrate deploy && node server.js"
    ports:
      - '3000:3000'
    volumes:
      - /mnt/map-photos:/app/photos
    restart: always
    networks:
      - photo_map_network

networks:
  photo_map_network:
    external: true
